name: dart_uuid
description: UUID type, parser and generators. Can generate v1, v4, and v5 UUIDs
version: 1.0.0
uploader: Jakub Bebenek <jakub.bebenek@gmail.com>
homepage: https://github.com/jakub100ful/dart-uuid
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.0
dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
